################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/boot/stm32_boot_xip.c \
/home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.c \
/home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/psram/stm32_psram_driver.c \
/home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_sd.c \
/home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_xspi.c \
/home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/sdcard/stm32_sdcard_driver.c \
/home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_data.c \
/home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_driver.c \
/home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/user/stm32_user_driver.c 

OBJS += \
./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.o \
./Middlewares/STM32_ExtMem_Manager/stm32_extmem.o \
./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.o \
./Middlewares/STM32_ExtMem_Manager/stm32_sal_sd.o \
./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.o \
./Middlewares/STM32_ExtMem_Manager/stm32_sdcard_driver.o \
./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.o \
./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.o \
./Middlewares/STM32_ExtMem_Manager/stm32_user_driver.o 

C_DEPS += \
./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.d \
./Middlewares/STM32_ExtMem_Manager/stm32_extmem.d \
./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.d \
./Middlewares/STM32_ExtMem_Manager/stm32_sal_sd.d \
./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.d \
./Middlewares/STM32_ExtMem_Manager/stm32_sdcard_driver.d \
./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.d \
./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.d \
./Middlewares/STM32_ExtMem_Manager/stm32_user_driver.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.o: /home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/boot/stm32_boot_xip.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S7xx -c -I../../../Boot/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../../../../../../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_extmem.o: /home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S7xx -c -I../../../Boot/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../../../../../../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.o: /home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/psram/stm32_psram_driver.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S7xx -c -I../../../Boot/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../../../../../../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_sal_sd.o: /home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_sd.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S7xx -c -I../../../Boot/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../../../../../../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.o: /home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_xspi.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S7xx -c -I../../../Boot/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../../../../../../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_sdcard_driver.o: /home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/sdcard/stm32_sdcard_driver.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S7xx -c -I../../../Boot/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../../../../../../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.o: /home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_data.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S7xx -c -I../../../Boot/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../../../../../../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.o: /home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_driver.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S7xx -c -I../../../Boot/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../../../../../../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_user_driver.o: /home/user/python_projects/EmbeddedX/projects/soot_detector/vendor_src/STM32CubeH7RS/Middlewares/ST/STM32_ExtMem_Manager/user/stm32_user_driver.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S7xx -c -I../../../Boot/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/boot -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../../../../../../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-STM32_ExtMem_Manager

clean-Middlewares-2f-STM32_ExtMem_Manager:
	-$(RM) ./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.d ./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.o ./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.su ./Middlewares/STM32_ExtMem_Manager/stm32_extmem.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_extmem.d ./Middlewares/STM32_ExtMem_Manager/stm32_extmem.o ./Middlewares/STM32_ExtMem_Manager/stm32_extmem.su ./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.d ./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.o ./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.su ./Middlewares/STM32_ExtMem_Manager/stm32_sal_sd.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_sal_sd.d ./Middlewares/STM32_ExtMem_Manager/stm32_sal_sd.o ./Middlewares/STM32_ExtMem_Manager/stm32_sal_sd.su ./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.d ./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.o ./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.su ./Middlewares/STM32_ExtMem_Manager/stm32_sdcard_driver.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_sdcard_driver.d ./Middlewares/STM32_ExtMem_Manager/stm32_sdcard_driver.o ./Middlewares/STM32_ExtMem_Manager/stm32_sdcard_driver.su ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.d ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.o ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.su ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.d ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.o ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.su ./Middlewares/STM32_ExtMem_Manager/stm32_user_driver.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_user_driver.d ./Middlewares/STM32_ExtMem_Manager/stm32_user_driver.o ./Middlewares/STM32_ExtMem_Manager/stm32_user_driver.su

.PHONY: clean-Middlewares-2f-STM32_ExtMem_Manager

